name: Validate Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ '**' ]  # This will match all branches

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Validate commit messages
        run: |
          # Get the commits to validate (either PR commits or push commits)
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            COMMITS=$(git log --format=%H ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          else
            # For push events, get the pushed commits
            COMMITS=$(git log --format=%H HEAD~10..HEAD)
          fi
          
          # Define a pattern that matches any commit message starting with [anything] 
          # with optional space after the closing bracket
          COMMIT_PATTERN="^\[.+\].*"
          
          # Validate each commit
          for COMMIT in $COMMITS; do
            MESSAGE=$(git log --format=%B -n 1 $COMMIT)
            if ! [[ $MESSAGE =~ $COMMIT_PATTERN ]]; then
              echo "Invalid commit message: $MESSAGE"
              echo "Commit messages must start with text in square brackets [ANY-TEXT]"
              exit 1
            fi
          done
          
          echo "All commit messages are valid!"